### ISSUE TITLE
question about project files

### ISSUE THREAD

**Issue by DmitriySheverda** [LAOS-Y/AgriVision#1]
Hello, where do the files agri-debug.odgt, agri-test.odgt, agri-trn.odgt,agri-val.odgt come from?? And I have to create the data folder myself and add all these files to it, am I right? Sorry for maybe stupid questions, I'm just a newbie.

**Comment by DTennant** [comment]
Hi， we have already updated the usage of odgt files in the README

**Comment by DmitriySheverda** [comment]
Thank you!
